[package]
name = "osrm-sys"
version = "0.1.0"
edition = "2024"
publish = true

[build-dependencies]
cmake = "0.1.54"
cc = "1.2.29"
reqwest = { version="0.12.22", features = ["blocking"] }
flate2 = "1.1.2"
tar = "0.4.44"
